mongo:
  image: mongo:4.0.9-xenial

server:
  build: .
  links:
    - mongo
  ports:
    - 8080:8080
  volumes:
    - /opt/media:/opt/media
    # Enable below only for Windows. If enabled, comment the line above
    # - C:/opus:/opt/media 