version: '3'
services:
  mongo:
    image: mongo:4.0.9-xenial
    ports:
      - 27017:27017
    restart: "always"

  opus-server:
    build: .
    links:
      - mongo
    ports:
      - 8080:8080
    volumes:
      - ~/opus/media:/opt/media
    restart: "always"
