version: '3'
services:
  mongo:
    container_name: opus-db
    image: mongo:4.0.9-xenial
    ports:
      - 27017:27017
    restart: "always"

  spotify-playlist-to-json:
    container_name: spotify-playlist-to-json
    build: https://github.com/dantheman213/spotify-playlist-to-json.git
    ports:
      - 3000:3000
    restart: "always"

  opus-server:
    container_name: opus-server
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
      - spotify-playlist-to-json
    depends_on:
      - mongo
      - spotify-playlist-to-json
    volumes:
      - ~/opus/media:/opt/media
    restart: "always"
